export const ERROR_CODES = {
  INVALID_INPUT: "INVALID_INPUT",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",

  SLUG_ALREADY_EXISTS: "SLUG_ALREADY_EXISTS",
  FOREIGN_KEY_VIOLATION: "FOREIGN_KEY_VIOLATION",

  UNKNOWN: "UNKNOWN",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
